# Generated by Django 3.1.1 on 2020-09-21 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_donated', models.FloatField(editable=False)),
                ('donated_on', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('bank_name', models.CharField(editable=False, max_length=25)),
                ('bank_branch', models.CharField(editable=False, max_length=50)),
                ('payment_method', models.CharField(choices=[('BankTransfer', 'BankTransfer'), ('PayTM', 'PayTM'), ('GooglePay', 'GooglePay'), ('CreditCard', 'CreditCard'), ('DebitCard', 'DebitCard')], editable=False, max_length=12)),
                ('donated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
