# Generated by Django 3.1.1 on 2020-09-21 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount_donated',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='bank_branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='bank_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donated_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('BankTransfer', 'BankTransfer'), ('PayTM', 'PayTM'), ('GooglePay', 'GooglePay'), ('CreditCard', 'CreditCard'), ('DebitCard', 'DebitCard')], max_length=12),
        ),
    ]
