# Generated by Django 3.1.1 on 2020-09-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_achievement_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='images',
        ),
        migrations.AddField(
            model_name='achievement',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
